# Generated by Django 4.0 on 2023-12-26 12:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default=api.models.generate_token, max_length=16, unique=True),
        ),
    ]
