# Generated by Django 4.0 on 2022-01-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='og_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
