# Generated by Django 4.0 on 2022-01-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_og_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='categery',
            new_name='category',
        ),
    ]
